"""rename address

Revision ID: 870d0bc4d4ff
Revises: 6032cbd6cbef
Create Date: 2025-05-13 06:31:31.101289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870d0bc4d4ff'
down_revision = '6032cbd6cbef'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###